/* Generated by re2c 0.12.3 */
#line 1 "src/sc_man_scanner.re"
#define	YYCTYPE		char
#define	YYCURSOR	cursor
#define	YYLIMIT		limit
#define	YYMARKER	marker
#define YYFILL(n)	{}
#if 0	// As long as the buffer ends with '\n', we need do nothing special for YYFILL.
	// This buffer must be as large as the largest YYFILL call
	YYCTYPE eofbuf[9];
#define	YYFILL(n)	\
	{ if(!sc_End) { \
	   if(n == 2) { eofbuf[0] = *cursor; } \
	   else if(n >= 3 && n <= 9) { memcpy(eofbuf, cursor, n-1); } \
	   eofbuf[n-1] = '\n'; \
	   cursor = eofbuf; \
	   limit = eofbuf + n - 1; \
	   sc_End = true; } \
	} \
	assert(n <= sizeof eofbuf)	// Semicolon intentionally omitted
#endif

//#define YYDEBUG(s,c) { Printf ("%d: %02x\n", s, c); }
#define YYDEBUG(s,c)

	const char *cursor = ScriptPtr;
	const char *limit = ScriptEndPtr;

std1:
	tok = YYCURSOR;
std2:
#line 51 "src/sc_man_scanner.re"

	if (tokens)	// A well-defined scanner, based on the c.re example.
	{
#define RET(x)	TokenType = x; goto normal_token;
	
#line 39 "src/sc_man_scanner.h"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if((YYLIMIT - YYCURSOR) < 18) YYFILL(18);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x09:
	case 0x0B:
	case 0x0C:
	case 0x0D:
	case ' ':	goto yy78;
	case 0x0A:	goto yy80;
	case '!':	goto yy54;
	case '"':	goto yy32;
	case '#':	goto yy24;
	case '%':	goto yy44;
	case '&':	goto yy46;
	case '\'':	goto yy33;
	case '(':	goto yy66;
	case ')':	goto yy68;
	case '*':	goto yy42;
	case '+':	goto yy38;
	case ',':	goto yy62;
	case '-':	goto yy40;
	case '.':	goto yy30;
	case '/':	goto yy2;
	case '0':	goto yy27;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy29;
	case ':':	goto yy64;
	case ';':	goto yy56;
	case '<':	goto yy36;
	case '=':	goto yy52;
	case '>':	goto yy34;
	case '?':	goto yy76;
	case 'A':
	case 'a':	goto yy20;
	case 'B':
	case 'b':	goto yy4;
	case 'C':
	case 'c':	goto yy6;
	case 'D':
	case 'd':	goto yy7;
	case 'E':
	case 'e':	goto yy8;
	case 'F':
	case 'f':	goto yy9;
	case 'G':
	case 'g':	goto yy10;
	case 'H':
	case 'J':
	case 'K':
	case 'Q':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'h':
	case 'j':
	case 'k':
	case 'q':
	case 'x':
	case 'y':
	case 'z':	goto yy26;
	case 'I':
	case 'i':	goto yy11;
	case 'L':
	case 'l':	goto yy17;
	case 'M':
	case 'm':	goto yy18;
	case 'N':
	case 'n':	goto yy19;
	case 'O':
	case 'o':	goto yy22;
	case 'P':
	case 'p':	goto yy23;
	case 'R':
	case 'r':	goto yy12;
	case 'S':
	case 's':	goto yy13;
	case 'T':
	case 't':	goto yy21;
	case 'U':
	case 'u':	goto yy14;
	case 'V':
	case 'v':	goto yy15;
	case 'W':
	case 'w':	goto yy16;
	case '[':	goto yy70;
	case ']':	goto yy72;
	case '^':	goto yy48;
	case '{':	goto yy58;
	case '|':	goto yy50;
	case '}':	goto yy60;
	case '~':	goto yy74;
	default:	goto yy82;
	}
yy2:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '.') {
		if(yych == '*') goto yy615;
	} else {
		if(yych <= '/') goto yy613;
		if(yych == '=') goto yy611;
	}
yy3:
#line 208 "src/sc_man_scanner.re"
	{ RET('/'); }
#line 157 "src/sc_man_scanner.h"
yy4:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Y') {
		if(yych <= 'Q') {
			if(yych == 'O') goto yy593;
			goto yy174;
		} else {
			if(yych <= 'R') goto yy594;
			if(yych <= 'X') goto yy174;
			goto yy595;
		}
	} else {
		if(yych <= 'q') {
			if(yych == 'o') goto yy593;
			goto yy174;
		} else {
			if(yych <= 'r') goto yy594;
			if(yych == 'y') goto yy595;
			goto yy174;
		}
	}
yy5:
#line 154 "src/sc_man_scanner.re"
	{ RET(TK_Identifier); }
#line 182 "src/sc_man_scanner.h"
yy6:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'A':
	case 'a':	goto yy551;
	case 'H':
	case 'h':	goto yy552;
	case 'L':
	case 'l':	goto yy553;
	case 'O':
	case 'o':	goto yy554;
	case 'R':
	case 'r':	goto yy555;
	default:	goto yy174;
	}
yy7:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych == 'E') goto yy524;
		if(yych <= 'N') goto yy174;
		goto yy525;
	} else {
		if(yych <= 'e') {
			if(yych <= 'd') goto yy174;
			goto yy524;
		} else {
			if(yych == 'o') goto yy525;
			goto yy174;
		}
	}
yy8:
	yych = *++YYCURSOR;
	if(yych <= 'X') {
		if(yych <= 'N') {
			if(yych == 'L') goto yy496;
			if(yych <= 'M') goto yy174;
			goto yy497;
		} else {
			if(yych == 'V') goto yy498;
			if(yych <= 'W') goto yy174;
			goto yy499;
		}
	} else {
		if(yych <= 'n') {
			if(yych == 'l') goto yy496;
			if(yych <= 'm') goto yy174;
			goto yy497;
		} else {
			if(yych <= 'v') {
				if(yych <= 'u') goto yy174;
				goto yy498;
			} else {
				if(yych == 'x') goto yy499;
				goto yy174;
			}
		}
	}
yy9:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych <= 'I') {
			if(yych == 'A') goto yy467;
			if(yych <= 'H') goto yy174;
			goto yy468;
		} else {
			if(yych == 'L') goto yy469;
			if(yych <= 'N') goto yy174;
			goto yy470;
		}
	} else {
		if(yych <= 'i') {
			if(yych == 'a') goto yy467;
			if(yych <= 'h') goto yy174;
			goto yy468;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy174;
				goto yy469;
			} else {
				if(yych == 'o') goto yy470;
				goto yy174;
			}
		}
	}
yy10:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych == 'L') goto yy457;
		if(yych <= 'N') goto yy174;
		goto yy458;
	} else {
		if(yych <= 'l') {
			if(yych <= 'k') goto yy174;
			goto yy457;
		} else {
			if(yych == 'o') goto yy458;
			goto yy174;
		}
	}
yy11:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych <= 'G') {
			if(yych <= 'E') goto yy174;
			if(yych <= 'F') goto yy428;
			goto yy430;
		} else {
			if(yych == 'N') goto yy431;
			if(yych <= 'S') goto yy174;
			goto yy432;
		}
	} else {
		if(yych <= 'm') {
			if(yych <= 'e') goto yy174;
			if(yych <= 'f') goto yy428;
			if(yych <= 'g') goto yy430;
			goto yy174;
		} else {
			if(yych <= 'n') goto yy431;
			if(yych == 't') goto yy432;
			goto yy174;
		}
	}
yy12:
	yych = *++YYCURSOR;
	if(yych <= 'E') {
		if(yych == 'A') goto yy412;
		if(yych <= 'D') goto yy174;
		goto yy413;
	} else {
		if(yych <= 'a') {
			if(yych <= '`') goto yy174;
			goto yy412;
		} else {
			if(yych == 'e') goto yy413;
			goto yy174;
		}
	}
yy13:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'B':
	case 'b':	goto yy354;
	case 'E':
	case 'e':	goto yy355;
	case 'H':
	case 'h':	goto yy356;
	case 'I':
	case 'i':	goto yy357;
	case 'O':
	case 'o':	goto yy358;
	case 'T':
	case 't':	goto yy359;
	case 'U':
	case 'u':	goto yy360;
	case 'W':
	case 'w':	goto yy361;
	default:	goto yy174;
	}
yy14:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'I':
	case 'i':	goto yy334;
	case 'L':
	case 'l':	goto yy335;
	case 'N':
	case 'n':	goto yy336;
	case 'S':
	case 's':	goto yy337;
	default:	goto yy174;
	}
yy15:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych == 'I') goto yy316;
		if(yych <= 'N') goto yy174;
		goto yy317;
	} else {
		if(yych <= 'i') {
			if(yych <= 'h') goto yy174;
			goto yy316;
		} else {
			if(yych == 'o') goto yy317;
			goto yy174;
		}
	}
yy16:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy311;
	if(yych == 'h') goto yy311;
	goto yy174;
yy17:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych == 'A') goto yy293;
		if(yych <= 'N') goto yy174;
		goto yy294;
	} else {
		if(yych <= 'a') {
			if(yych <= '`') goto yy174;
			goto yy293;
		} else {
			if(yych == 'o') goto yy294;
			goto yy174;
		}
	}
yy18:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy289;
	if(yych == 'o') goto yy289;
	goto yy174;
yy19:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych <= 'D') {
			if(yych == 'A') goto yy273;
			goto yy174;
		} else {
			if(yych <= 'E') goto yy274;
			if(yych <= 'N') goto yy174;
			goto yy275;
		}
	} else {
		if(yych <= 'd') {
			if(yych == 'a') goto yy273;
			goto yy174;
		} else {
			if(yych <= 'e') goto yy274;
			if(yych == 'o') goto yy275;
			goto yy174;
		}
	}
yy20:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych <= 'C') {
			if(yych <= 'A') goto yy174;
			if(yych <= 'B') goto yy247;
			goto yy248;
		} else {
			if(yych == 'N') goto yy249;
			if(yych <= 'T') goto yy174;
			goto yy250;
		}
	} else {
		if(yych <= 'm') {
			if(yych <= 'a') goto yy174;
			if(yych <= 'b') goto yy247;
			if(yych <= 'c') goto yy248;
			goto yy174;
		} else {
			if(yych <= 'n') goto yy249;
			if(yych == 'u') goto yy250;
			goto yy174;
		}
	}
yy21:
	yych = *++YYCURSOR;
	if(yych <= 'R') {
		if(yych == 'H') goto yy229;
		if(yych <= 'Q') goto yy174;
		goto yy230;
	} else {
		if(yych <= 'h') {
			if(yych <= 'g') goto yy174;
			goto yy229;
		} else {
			if(yych == 'r') goto yy230;
			goto yy174;
		}
	}
yy22:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych == 'P') goto yy218;
		if(yych <= 'T') goto yy174;
		goto yy219;
	} else {
		if(yych <= 'p') {
			if(yych <= 'o') goto yy174;
			goto yy218;
		} else {
			if(yych == 'u') goto yy219;
			goto yy174;
		}
	}
yy23:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych <= 'Q') {
			if(yych == 'I') goto yy183;
			goto yy174;
		} else {
			if(yych <= 'R') goto yy184;
			if(yych <= 'T') goto yy174;
			goto yy185;
		}
	} else {
		if(yych <= 'q') {
			if(yych == 'i') goto yy183;
			goto yy174;
		} else {
			if(yych <= 'r') goto yy184;
			if(yych == 'u') goto yy185;
			goto yy174;
		}
	}
yy24:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'I') goto yy175;
	if(yych == 'i') goto yy175;
yy25:
#line 219 "src/sc_man_scanner.re"
	{
			ScriptError ("Unexpected character: %c (ASCII %d)\n", *tok, *tok);
			goto std1;
		}
#line 502 "src/sc_man_scanner.h"
yy26:
	yych = *++YYCURSOR;
	goto yy174;
yy27:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'X') goto yy170;
	if(yych == 'x') goto yy170;
	goto yy169;
yy28:
#line 157 "src/sc_man_scanner.re"
	{ RET(TK_IntConst); }
#line 515 "src/sc_man_scanner.h"
yy29:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy152;
yy30:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '.') goto yy139;
	if(yych <= '/') goto yy31;
	if(yych <= '9') goto yy140;
yy31:
#line 201 "src/sc_man_scanner.re"
	{ RET('.'); }
#line 529 "src/sc_man_scanner.h"
yy32:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy133;
yy33:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 0x0A) goto yy25;
	goto yy128;
yy34:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '<') goto yy35;
	if(yych <= '=') goto yy117;
	if(yych <= '>') goto yy119;
yy35:
#line 211 "src/sc_man_scanner.re"
	{ RET('>'); }
#line 547 "src/sc_man_scanner.h"
yy36:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ';') goto yy37;
	if(yych <= '<') goto yy113;
	if(yych <= '=') goto yy111;
yy37:
#line 210 "src/sc_man_scanner.re"
	{ RET('<'); }
#line 556 "src/sc_man_scanner.h"
yy38:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '+') goto yy107;
	if(yych == '=') goto yy109;
#line 206 "src/sc_man_scanner.re"
	{ RET('+'); }
#line 563 "src/sc_man_scanner.h"
yy40:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '-') goto yy103;
	if(yych == '=') goto yy105;
#line 205 "src/sc_man_scanner.re"
	{ RET('-'); }
#line 570 "src/sc_man_scanner.h"
yy42:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy101;
#line 207 "src/sc_man_scanner.re"
	{ RET('*'); }
#line 576 "src/sc_man_scanner.h"
yy44:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy99;
#line 209 "src/sc_man_scanner.re"
	{ RET('%'); }
#line 582 "src/sc_man_scanner.h"
yy46:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '&') goto yy95;
	if(yych == '=') goto yy97;
#line 202 "src/sc_man_scanner.re"
	{ RET('&'); }
#line 589 "src/sc_man_scanner.h"
yy48:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy93;
#line 212 "src/sc_man_scanner.re"
	{ RET('^'); }
#line 595 "src/sc_man_scanner.h"
yy50:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy91;
	if(yych == '|') goto yy89;
#line 213 "src/sc_man_scanner.re"
	{ RET('|'); }
#line 602 "src/sc_man_scanner.h"
yy52:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy87;
#line 196 "src/sc_man_scanner.re"
	{ RET('='); }
#line 608 "src/sc_man_scanner.h"
yy54:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy85;
#line 203 "src/sc_man_scanner.re"
	{ RET('!'); }
#line 614 "src/sc_man_scanner.h"
yy56:
	++YYCURSOR;
#line 191 "src/sc_man_scanner.re"
	{ RET(';'); }
#line 619 "src/sc_man_scanner.h"
yy58:
	++YYCURSOR;
#line 192 "src/sc_man_scanner.re"
	{ RET('{'); }
#line 624 "src/sc_man_scanner.h"
yy60:
	++YYCURSOR;
#line 193 "src/sc_man_scanner.re"
	{ RET('}'); }
#line 629 "src/sc_man_scanner.h"
yy62:
	++YYCURSOR;
#line 194 "src/sc_man_scanner.re"
	{ RET(','); }
#line 634 "src/sc_man_scanner.h"
yy64:
	++YYCURSOR;
#line 195 "src/sc_man_scanner.re"
	{ RET(':'); }
#line 639 "src/sc_man_scanner.h"
yy66:
	++YYCURSOR;
#line 197 "src/sc_man_scanner.re"
	{ RET('('); }
#line 644 "src/sc_man_scanner.h"
yy68:
	++YYCURSOR;
#line 198 "src/sc_man_scanner.re"
	{ RET(')'); }
#line 649 "src/sc_man_scanner.h"
yy70:
	++YYCURSOR;
#line 199 "src/sc_man_scanner.re"
	{ RET('['); }
#line 654 "src/sc_man_scanner.h"
yy72:
	++YYCURSOR;
#line 200 "src/sc_man_scanner.re"
	{ RET(']'); }
#line 659 "src/sc_man_scanner.h"
yy74:
	++YYCURSOR;
#line 204 "src/sc_man_scanner.re"
	{ RET('~'); }
#line 664 "src/sc_man_scanner.h"
yy76:
	++YYCURSOR;
#line 214 "src/sc_man_scanner.re"
	{ RET('?'); }
#line 669 "src/sc_man_scanner.h"
yy78:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy84;
yy79:
#line 216 "src/sc_man_scanner.re"
	{ goto std1; }
#line 677 "src/sc_man_scanner.h"
yy80:
	++YYCURSOR;
#line 217 "src/sc_man_scanner.re"
	{ goto newline; }
#line 682 "src/sc_man_scanner.h"
yy82:
	yych = *++YYCURSOR;
	goto yy25;
yy83:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy84:
	if(yych <= 0x0A) {
		if(yych == 0x09) goto yy83;
		goto yy79;
	} else {
		if(yych <= 0x0D) goto yy83;
		if(yych == ' ') goto yy83;
		goto yy79;
	}
yy85:
	++YYCURSOR;
#line 190 "src/sc_man_scanner.re"
	{ RET(TK_Neq); }
#line 703 "src/sc_man_scanner.h"
yy87:
	++YYCURSOR;
#line 189 "src/sc_man_scanner.re"
	{ RET(TK_Eq); }
#line 708 "src/sc_man_scanner.h"
yy89:
	++YYCURSOR;
#line 186 "src/sc_man_scanner.re"
	{ RET(TK_OrOr); }
#line 713 "src/sc_man_scanner.h"
yy91:
	++YYCURSOR;
#line 179 "src/sc_man_scanner.re"
	{ RET(TK_OrEq); }
#line 718 "src/sc_man_scanner.h"
yy93:
	++YYCURSOR;
#line 178 "src/sc_man_scanner.re"
	{ RET(TK_XorEq); }
#line 723 "src/sc_man_scanner.h"
yy95:
	++YYCURSOR;
#line 185 "src/sc_man_scanner.re"
	{ RET(TK_AndAnd); }
#line 728 "src/sc_man_scanner.h"
yy97:
	++YYCURSOR;
#line 177 "src/sc_man_scanner.re"
	{ RET(TK_AndEq); }
#line 733 "src/sc_man_scanner.h"
yy99:
	++YYCURSOR;
#line 176 "src/sc_man_scanner.re"
	{ RET(TK_ModEq); }
#line 738 "src/sc_man_scanner.h"
yy101:
	++YYCURSOR;
#line 174 "src/sc_man_scanner.re"
	{ RET(TK_MulEq); }
#line 743 "src/sc_man_scanner.h"
yy103:
	++YYCURSOR;
#line 184 "src/sc_man_scanner.re"
	{ RET(TK_Decr); }
#line 748 "src/sc_man_scanner.h"
yy105:
	++YYCURSOR;
#line 173 "src/sc_man_scanner.re"
	{ RET(TK_SubEq); }
#line 753 "src/sc_man_scanner.h"
yy107:
	++YYCURSOR;
#line 183 "src/sc_man_scanner.re"
	{ RET(TK_Incr); }
#line 758 "src/sc_man_scanner.h"
yy109:
	++YYCURSOR;
#line 172 "src/sc_man_scanner.re"
	{ RET(TK_AddEq); }
#line 763 "src/sc_man_scanner.h"
yy111:
	++YYCURSOR;
#line 187 "src/sc_man_scanner.re"
	{ RET(TK_Leq); }
#line 768 "src/sc_man_scanner.h"
yy113:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy115;
#line 182 "src/sc_man_scanner.re"
	{ RET(TK_LShift); }
#line 774 "src/sc_man_scanner.h"
yy115:
	++YYCURSOR;
#line 171 "src/sc_man_scanner.re"
	{ RET(TK_LShiftEq); }
#line 779 "src/sc_man_scanner.h"
yy117:
	++YYCURSOR;
#line 188 "src/sc_man_scanner.re"
	{ RET(TK_Geq); }
#line 784 "src/sc_man_scanner.h"
yy119:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '<') goto yy120;
	if(yych <= '=') goto yy123;
	if(yych <= '>') goto yy121;
yy120:
#line 181 "src/sc_man_scanner.re"
	{ RET(TK_RShift); }
#line 793 "src/sc_man_scanner.h"
yy121:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy125;
#line 180 "src/sc_man_scanner.re"
	{ RET(TK_URShift); }
#line 799 "src/sc_man_scanner.h"
yy123:
	++YYCURSOR;
#line 170 "src/sc_man_scanner.re"
	{ RET(TK_RShiftEq); }
#line 804 "src/sc_man_scanner.h"
yy125:
	++YYCURSOR;
#line 169 "src/sc_man_scanner.re"
	{ RET(TK_URShiftEq); }
#line 809 "src/sc_man_scanner.h"
yy127:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy128:
	if(yych == 0x0A) goto yy129;
	if(yych == '\'') goto yy130;
	goto yy127;
yy129:
	YYCURSOR = YYMARKER;
	if(yyaccept <= 2) {
		if(yyaccept <= 1) {
			if(yyaccept <= 0) {
				goto yy3;
			} else {
				goto yy25;
			}
		} else {
			goto yy28;
		}
	} else {
		if(yyaccept <= 4) {
			if(yyaccept <= 3) {
				goto yy31;
			} else {
				goto yy137;
			}
		} else {
			goto yy142;
		}
	}
yy130:
	++YYCURSOR;
#line 166 "src/sc_man_scanner.re"
	{ RET(TK_NameConst); }
#line 845 "src/sc_man_scanner.h"
yy132:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy133:
	if(yych == '"') goto yy136;
	if(yych != '\\') goto yy132;
yy134:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '"') goto yy138;
	if(yych == '\\') goto yy134;
	goto yy132;
yy136:
	++YYCURSOR;
yy137:
#line 163 "src/sc_man_scanner.re"
	{ RET(TK_StringConst); }
#line 865 "src/sc_man_scanner.h"
yy138:
	yyaccept = 4;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '"') goto yy136;
	if(yych == '\\') goto yy134;
	goto yy132;
yy139:
	yych = *++YYCURSOR;
	if(yych == '.') goto yy148;
	goto yy129;
yy140:
	yyaccept = 5;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if(yych <= 'K') {
		if(yych <= 'D') {
			if(yych <= '/') goto yy142;
			if(yych <= '9') goto yy140;
		} else {
			if(yych <= 'E') goto yy143;
			if(yych <= 'F') goto yy144;
		}
	} else {
		if(yych <= 'e') {
			if(yych <= 'L') goto yy144;
			if(yych >= 'e') goto yy143;
		} else {
			if(yych <= 'f') goto yy144;
			if(yych == 'l') goto yy144;
		}
	}
yy142:
#line 160 "src/sc_man_scanner.re"
	{ RET(TK_FloatConst); }
#line 903 "src/sc_man_scanner.h"
yy143:
	yych = *++YYCURSOR;
	if(yych <= ',') {
		if(yych == '+') goto yy145;
		goto yy129;
	} else {
		if(yych <= '-') goto yy145;
		if(yych <= '/') goto yy129;
		if(yych <= '9') goto yy146;
		goto yy129;
	}
yy144:
	yych = *++YYCURSOR;
	goto yy142;
yy145:
	yych = *++YYCURSOR;
	if(yych <= '/') goto yy129;
	if(yych >= ':') goto yy129;
yy146:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'K') {
		if(yych <= '9') {
			if(yych <= '/') goto yy142;
			goto yy146;
		} else {
			if(yych == 'F') goto yy144;
			goto yy142;
		}
	} else {
		if(yych <= 'f') {
			if(yych <= 'L') goto yy144;
			if(yych <= 'e') goto yy142;
			goto yy144;
		} else {
			if(yych == 'l') goto yy144;
			goto yy142;
		}
	}
yy148:
	++YYCURSOR;
#line 168 "src/sc_man_scanner.re"
	{ RET(TK_Ellipsis); }
#line 948 "src/sc_man_scanner.h"
yy150:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'E') goto yy160;
	if(yych == 'e') goto yy160;
	goto yy159;
yy151:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy152:
	if(yych <= 'L') {
		if(yych <= '9') {
			if(yych == '.') goto yy150;
			if(yych <= '/') goto yy28;
			goto yy151;
		} else {
			if(yych == 'E') goto yy153;
			if(yych <= 'K') goto yy28;
			goto yy154;
		}
	} else {
		if(yych <= 'e') {
			if(yych == 'U') goto yy154;
			if(yych <= 'd') goto yy28;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy28;
				goto yy154;
			} else {
				if(yych == 'u') goto yy154;
				goto yy28;
			}
		}
	}
yy153:
	yych = *++YYCURSOR;
	if(yych <= ',') {
		if(yych == '+') goto yy155;
		goto yy129;
	} else {
		if(yych <= '-') goto yy155;
		if(yych <= '/') goto yy129;
		if(yych <= '9') goto yy156;
		goto yy129;
	}
yy154:
	yych = *++YYCURSOR;
	goto yy28;
yy155:
	yych = *++YYCURSOR;
	if(yych <= '/') goto yy129;
	if(yych >= ':') goto yy129;
yy156:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'K') {
		if(yych <= '9') {
			if(yych <= '/') goto yy142;
			goto yy156;
		} else {
			if(yych == 'F') goto yy144;
			goto yy142;
		}
	} else {
		if(yych <= 'f') {
			if(yych <= 'L') goto yy144;
			if(yych <= 'e') goto yy142;
			goto yy144;
		} else {
			if(yych == 'l') goto yy144;
			goto yy142;
		}
	}
yy158:
	yyaccept = 5;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy159:
	if(yych <= 'K') {
		if(yych <= 'D') {
			if(yych <= '/') goto yy142;
			if(yych <= '9') goto yy158;
			goto yy142;
		} else {
			if(yych <= 'E') goto yy164;
			if(yych <= 'F') goto yy144;
			goto yy142;
		}
	} else {
		if(yych <= 'e') {
			if(yych <= 'L') goto yy144;
			if(yych <= 'd') goto yy142;
			goto yy164;
		} else {
			if(yych <= 'f') goto yy144;
			if(yych == 'l') goto yy144;
			goto yy142;
		}
	}
yy160:
	yych = *++YYCURSOR;
	if(yych <= ',') {
		if(yych != '+') goto yy129;
	} else {
		if(yych <= '-') goto yy161;
		if(yych <= '/') goto yy129;
		if(yych <= '9') goto yy162;
		goto yy129;
	}
yy161:
	yych = *++YYCURSOR;
	if(yych <= '/') goto yy129;
	if(yych >= ':') goto yy129;
yy162:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'K') {
		if(yych <= '9') {
			if(yych <= '/') goto yy142;
			goto yy162;
		} else {
			if(yych == 'F') goto yy144;
			goto yy142;
		}
	} else {
		if(yych <= 'f') {
			if(yych <= 'L') goto yy144;
			if(yych <= 'e') goto yy142;
			goto yy144;
		} else {
			if(yych == 'l') goto yy144;
			goto yy142;
		}
	}
yy164:
	yych = *++YYCURSOR;
	if(yych <= ',') {
		if(yych != '+') goto yy129;
	} else {
		if(yych <= '-') goto yy165;
		if(yych <= '/') goto yy129;
		if(yych <= '9') goto yy166;
		goto yy129;
	}
yy165:
	yych = *++YYCURSOR;
	if(yych <= '/') goto yy129;
	if(yych >= ':') goto yy129;
yy166:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'K') {
		if(yych <= '9') {
			if(yych <= '/') goto yy142;
			goto yy166;
		} else {
			if(yych == 'F') goto yy144;
			goto yy142;
		}
	} else {
		if(yych <= 'f') {
			if(yych <= 'L') goto yy144;
			if(yych <= 'e') goto yy142;
			goto yy144;
		} else {
			if(yych == 'l') goto yy144;
			goto yy142;
		}
	}
yy168:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy169:
	if(yych <= 'L') {
		if(yych <= '9') {
			if(yych == '.') goto yy150;
			if(yych <= '/') goto yy28;
			goto yy168;
		} else {
			if(yych == 'E') goto yy153;
			if(yych <= 'K') goto yy28;
			goto yy154;
		}
	} else {
		if(yych <= 'e') {
			if(yych == 'U') goto yy154;
			if(yych <= 'd') goto yy28;
			goto yy153;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy28;
				goto yy154;
			} else {
				if(yych == 'u') goto yy154;
				goto yy28;
			}
		}
	}
yy170:
	yych = *++YYCURSOR;
	if(yych <= '@') {
		if(yych <= '/') goto yy129;
		if(yych >= ':') goto yy129;
	} else {
		if(yych <= 'F') goto yy171;
		if(yych <= '`') goto yy129;
		if(yych >= 'g') goto yy129;
	}
yy171:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'T') {
		if(yych <= '@') {
			if(yych <= '/') goto yy28;
			if(yych <= '9') goto yy171;
			goto yy28;
		} else {
			if(yych <= 'F') goto yy171;
			if(yych == 'L') goto yy154;
			goto yy28;
		}
	} else {
		if(yych <= 'k') {
			if(yych <= 'U') goto yy154;
			if(yych <= '`') goto yy28;
			if(yych <= 'f') goto yy171;
			goto yy28;
		} else {
			if(yych <= 'l') goto yy154;
			if(yych == 'u') goto yy154;
			goto yy28;
		}
	}
yy173:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy174:
	if(yych <= 'Z') {
		if(yych <= '/') goto yy5;
		if(yych <= '9') goto yy173;
		if(yych <= '@') goto yy5;
		goto yy173;
	} else {
		if(yych <= '_') {
			if(yych <= '^') goto yy5;
			goto yy173;
		} else {
			if(yych <= '`') goto yy5;
			if(yych <= 'z') goto yy173;
			goto yy5;
		}
	}
yy175:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy176;
	if(yych != 'n') goto yy129;
yy176:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy177;
	if(yych != 'c') goto yy129;
yy177:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy178;
	if(yych != 'l') goto yy129;
yy178:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy179;
	if(yych != 'u') goto yy129;
yy179:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy180;
	if(yych != 'd') goto yy129;
yy180:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy181;
	if(yych != 'e') goto yy129;
yy181:
	++YYCURSOR;
#line 144 "src/sc_man_scanner.re"
	{ RET(TK_Include); }
#line 1239 "src/sc_man_scanner.h"
yy183:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy213;
	if(yych == 'c') goto yy213;
	goto yy174;
yy184:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych == 'I') goto yy192;
		if(yych <= 'N') goto yy174;
		goto yy191;
	} else {
		if(yych <= 'i') {
			if(yych <= 'h') goto yy174;
			goto yy192;
		} else {
			if(yych == 'o') goto yy191;
			goto yy174;
		}
	}
yy185:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy186;
	if(yych != 'b') goto yy174;
yy186:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy187;
	if(yych != 'l') goto yy174;
yy187:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy188;
	if(yych != 'i') goto yy174;
yy188:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy189;
	if(yych != 'c') goto yy174;
yy189:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy190;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy190;
			if(yych <= 'z') goto yy173;
		}
	}
yy190:
#line 120 "src/sc_man_scanner.re"
	{ RET(TK_Public); }
#line 1293 "src/sc_man_scanner.h"
yy191:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych == 'J') goto yy198;
		if(yych <= 'S') goto yy174;
		goto yy199;
	} else {
		if(yych <= 'j') {
			if(yych <= 'i') goto yy174;
			goto yy198;
		} else {
			if(yych == 't') goto yy199;
			goto yy174;
		}
	}
yy192:
	yych = *++YYCURSOR;
	if(yych == 'V') goto yy193;
	if(yych != 'v') goto yy174;
yy193:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy194;
	if(yych != 'a') goto yy174;
yy194:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy195;
	if(yych != 't') goto yy174;
yy195:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy196;
	if(yych != 'e') goto yy174;
yy196:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy197;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy197;
			if(yych <= 'z') goto yy173;
		}
	}
yy197:
#line 122 "src/sc_man_scanner.re"
	{ RET(TK_Private); }
#line 1342 "src/sc_man_scanner.h"
yy198:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy206;
	if(yych == 'e') goto yy206;
	goto yy174;
yy199:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy200;
	if(yych != 'e') goto yy174;
yy200:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy201;
	if(yych != 'c') goto yy174;
yy201:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy202;
	if(yych != 't') goto yy174;
yy202:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy203;
	if(yych != 'e') goto yy174;
yy203:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy204;
	if(yych != 'd') goto yy174;
yy204:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy205;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy205;
			if(yych <= 'z') goto yy173;
		}
	}
yy205:
#line 121 "src/sc_man_scanner.re"
	{ RET(TK_Protected); }
#line 1385 "src/sc_man_scanner.h"
yy206:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy207;
	if(yych != 'c') goto yy174;
yy207:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy208;
	if(yych != 't') goto yy174;
yy208:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy209;
	if(yych != 'i') goto yy174;
yy209:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy210;
	if(yych != 'l') goto yy174;
yy210:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy211;
	if(yych != 'e') goto yy174;
yy211:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy212;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy212;
			if(yych <= 'z') goto yy173;
		}
	}
yy212:
#line 147 "src/sc_man_scanner.re"
	{ RET(TK_Projectile); }
#line 1423 "src/sc_man_scanner.h"
yy213:
	yych = *++YYCURSOR;
	if(yych == 'K') goto yy214;
	if(yych != 'k') goto yy174;
yy214:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy215;
	if(yych != 'u') goto yy174;
yy215:
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy216;
	if(yych != 'p') goto yy174;
yy216:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy217;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy217;
			if(yych <= 'z') goto yy173;
		}
	}
yy217:
#line 145 "src/sc_man_scanner.re"
	{ RET(TK_Pickup); }
#line 1453 "src/sc_man_scanner.h"
yy218:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy222;
	if(yych == 't') goto yy222;
	goto yy174;
yy219:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy220;
	if(yych != 't') goto yy174;
yy220:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy221;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy221;
			if(yych <= 'z') goto yy173;
		}
	}
yy221:
#line 112 "src/sc_man_scanner.re"
	{ RET(TK_Out); }
#line 1480 "src/sc_man_scanner.h"
yy222:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy223;
	if(yych != 'i') goto yy174;
yy223:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy224;
	if(yych != 'o') goto yy174;
yy224:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy225;
	if(yych != 'n') goto yy174;
yy225:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy226;
	if(yych != 'a') goto yy174;
yy226:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy227;
	if(yych != 'l') goto yy174;
yy227:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy228;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy228;
			if(yych <= 'z') goto yy173;
		}
	}
yy228:
#line 132 "src/sc_man_scanner.re"
	{ RET(TK_Optional); }
#line 1518 "src/sc_man_scanner.h"
yy229:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy242;
	if(yych == 'r') goto yy242;
	goto yy174;
yy230:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych == 'A') goto yy232;
		if(yych <= 'T') goto yy174;
	} else {
		if(yych <= 'a') {
			if(yych <= '`') goto yy174;
			goto yy232;
		} else {
			if(yych != 'u') goto yy174;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy240;
	if(yych == 'e') goto yy240;
	goto yy174;
yy232:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy233;
	if(yych != 'n') goto yy174;
yy233:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy234;
	if(yych != 's') goto yy174;
yy234:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy235;
	if(yych != 'i') goto yy174;
yy235:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy236;
	if(yych != 'e') goto yy174;
yy236:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy237;
	if(yych != 'n') goto yy174;
yy237:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy238;
	if(yych != 't') goto yy174;
yy238:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy239;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy239;
			if(yych <= 'z') goto yy173;
		}
	}
yy239:
#line 116 "src/sc_man_scanner.re"
	{ RET(TK_Transient); }
#line 1582 "src/sc_man_scanner.h"
yy240:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy241;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy241;
			if(yych <= 'z') goto yy173;
		}
	}
yy241:
#line 103 "src/sc_man_scanner.re"
	{ RET(TK_True); }
#line 1600 "src/sc_man_scanner.h"
yy242:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy243;
	if(yych != 'o') goto yy174;
yy243:
	yych = *++YYCURSOR;
	if(yych == 'W') goto yy244;
	if(yych != 'w') goto yy174;
yy244:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy245;
	if(yych != 's') goto yy174;
yy245:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy246;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy246;
			if(yych <= 'z') goto yy173;
		}
	}
yy246:
#line 118 "src/sc_man_scanner.re"
	{ RET(TK_Throws); }
#line 1630 "src/sc_man_scanner.h"
yy247:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy265;
	if(yych == 's') goto yy265;
	goto yy174;
yy248:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy260;
	if(yych == 't') goto yy260;
	goto yy174;
yy249:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy254;
	if(yych == 'g') goto yy254;
	goto yy174;
yy250:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy251;
	if(yych != 't') goto yy174;
yy251:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy252;
	if(yych != 'o') goto yy174;
yy252:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy253;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy253;
			if(yych <= 'z') goto yy173;
		}
	}
yy253:
#line 108 "src/sc_man_scanner.re"
	{ RET(TK_Auto); }
#line 1671 "src/sc_man_scanner.h"
yy254:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy255;
	if(yych != 'l') goto yy174;
yy255:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy256;
	if(yych != 'e') goto yy174;
yy256:
	yych = *++YYCURSOR;
	if(yych != '_') goto yy174;
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy258;
	if(yych != 't') goto yy174;
yy258:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy259;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy259;
			if(yych <= 'z') goto yy173;
		}
	}
yy259:
#line 149 "src/sc_man_scanner.re"
	{ RET(TK_Angle_t); }
#line 1703 "src/sc_man_scanner.h"
yy260:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy261;
	if(yych != 'i') goto yy174;
yy261:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy262;
	if(yych != 'o') goto yy174;
yy262:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy263;
	if(yych != 'n') goto yy174;
yy263:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy264;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy264;
			if(yych <= 'z') goto yy173;
		}
	}
yy264:
#line 141 "src/sc_man_scanner.re"
	{ RET(TK_Action); }
#line 1733 "src/sc_man_scanner.h"
yy265:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '@') {
			if(yych <= '/') goto yy266;
			if(yych <= '9') goto yy173;
		} else {
			if(yych == 'T') goto yy267;
			goto yy173;
		}
	} else {
		if(yych <= '`') {
			if(yych == '_') goto yy173;
		} else {
			if(yych == 't') goto yy267;
			if(yych <= 'z') goto yy173;
		}
	}
yy266:
#line 150 "src/sc_man_scanner.re"
	{ RET(TK_Abs); }
#line 1755 "src/sc_man_scanner.h"
yy267:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy268;
	if(yych != 'r') goto yy174;
yy268:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy269;
	if(yych != 'a') goto yy174;
yy269:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy270;
	if(yych != 'c') goto yy174;
yy270:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy271;
	if(yych != 't') goto yy174;
yy271:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy272;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy272;
			if(yych <= 'z') goto yy173;
		}
	}
yy272:
#line 101 "src/sc_man_scanner.re"
	{ RET(TK_Abstract); }
#line 1789 "src/sc_man_scanner.h"
yy273:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych == 'M') goto yy281;
		if(yych <= 'S') goto yy174;
		goto yy282;
	} else {
		if(yych <= 'm') {
			if(yych <= 'l') goto yy174;
			goto yy281;
		} else {
			if(yych == 't') goto yy282;
			goto yy174;
		}
	}
yy274:
	yych = *++YYCURSOR;
	if(yych == 'W') goto yy279;
	if(yych == 'w') goto yy279;
	goto yy174;
yy275:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy276;
	if(yych != 'n') goto yy174;
yy276:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy277;
	if(yych != 'e') goto yy174;
yy277:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy278;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy278;
			if(yych <= 'z') goto yy173;
		}
	}
yy278:
#line 105 "src/sc_man_scanner.re"
	{ RET(TK_None); }
#line 1835 "src/sc_man_scanner.h"
yy279:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy280;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy280;
			if(yych <= 'z') goto yy173;
		}
	}
yy280:
#line 106 "src/sc_man_scanner.re"
	{ RET(TK_New); }
#line 1853 "src/sc_man_scanner.h"
yy281:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy287;
	if(yych == 'e') goto yy287;
	goto yy174;
yy282:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy283;
	if(yych != 'i') goto yy174;
yy283:
	yych = *++YYCURSOR;
	if(yych == 'V') goto yy284;
	if(yych != 'v') goto yy174;
yy284:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy285;
	if(yych != 'e') goto yy174;
yy285:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy286;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy286;
			if(yych <= 'z') goto yy173;
		}
	}
yy286:
#line 111 "src/sc_man_scanner.re"
	{ RET(TK_Native); }
#line 1888 "src/sc_man_scanner.h"
yy287:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy288;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy288;
			if(yych <= 'z') goto yy173;
		}
	}
yy288:
#line 94 "src/sc_man_scanner.re"
	{ RET(TK_Name); }
#line 1906 "src/sc_man_scanner.h"
yy289:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy290;
	if(yych != 'd') goto yy174;
yy290:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy291;
	if(yych != 'e') goto yy174;
yy291:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy292;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy292;
			if(yych <= 'z') goto yy173;
		}
	}
yy292:
#line 92 "src/sc_man_scanner.re"
	{ RET(TK_Mode); }
#line 1932 "src/sc_man_scanner.h"
yy293:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy306;
	if(yych == 't') goto yy306;
	goto yy174;
yy294:
	yych = *++YYCURSOR;
	if(yych <= 'N') {
		if(yych == 'C') goto yy296;
		if(yych <= 'M') goto yy174;
	} else {
		if(yych <= 'c') {
			if(yych <= 'b') goto yy174;
			goto yy296;
		} else {
			if(yych != 'n') goto yy174;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy304;
	if(yych == 'g') goto yy304;
	goto yy174;
yy296:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy297;
	if(yych != 'a') goto yy174;
yy297:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy298;
	if(yych != 'l') goto yy174;
yy298:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy299;
	if(yych != 'i') goto yy174;
yy299:
	yych = *++YYCURSOR;
	if(yych == 'Z') goto yy300;
	if(yych != 'z') goto yy174;
yy300:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy301;
	if(yych != 'e') goto yy174;
yy301:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy302;
	if(yych != 'd') goto yy174;
yy302:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy303;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy303;
			if(yych <= 'z') goto yy173;
		}
	}
yy303:
#line 126 "src/sc_man_scanner.re"
	{ RET(TK_Localized); }
#line 1996 "src/sc_man_scanner.h"
yy304:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy305;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy305;
			if(yych <= 'z') goto yy173;
		}
	}
yy305:
#line 87 "src/sc_man_scanner.re"
	{ RET(TK_Long); }
#line 2014 "src/sc_man_scanner.h"
yy306:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy307;
	if(yych != 'e') goto yy174;
yy307:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy308;
	if(yych != 'n') goto yy174;
yy308:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy309;
	if(yych != 't') goto yy174;
yy309:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy310;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy310;
			if(yych <= 'z') goto yy173;
		}
	}
yy310:
#line 127 "src/sc_man_scanner.re"
	{ RET(TK_Latent); }
#line 2044 "src/sc_man_scanner.h"
yy311:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy312;
	if(yych != 'i') goto yy174;
yy312:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy313;
	if(yych != 'l') goto yy174;
yy313:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy314;
	if(yych != 'e') goto yy174;
yy314:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy315;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy315;
			if(yych <= 'z') goto yy173;
		}
	}
yy315:
#line 74 "src/sc_man_scanner.re"
	{ RET(TK_While); }
#line 2074 "src/sc_man_scanner.h"
yy316:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy328;
	if(yych == 'r') goto yy328;
	goto yy174;
yy317:
	yych = *++YYCURSOR;
	if(yych <= 'L') {
		if(yych == 'I') goto yy319;
		if(yych <= 'K') goto yy174;
	} else {
		if(yych <= 'i') {
			if(yych <= 'h') goto yy174;
			goto yy319;
		} else {
			if(yych != 'l') goto yy174;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy322;
	if(yych == 'a') goto yy322;
	goto yy174;
yy319:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy320;
	if(yych != 'd') goto yy174;
yy320:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy321;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy321;
			if(yych <= 'z') goto yy173;
		}
	}
yy321:
#line 89 "src/sc_man_scanner.re"
	{ RET(TK_Void); }
#line 2118 "src/sc_man_scanner.h"
yy322:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy323;
	if(yych != 't') goto yy174;
yy323:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy324;
	if(yych != 'i') goto yy174;
yy324:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy325;
	if(yych != 'l') goto yy174;
yy325:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy326;
	if(yych != 'e') goto yy174;
yy326:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy327;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy327;
			if(yych <= 'z') goto yy173;
		}
	}
yy327:
#line 73 "src/sc_man_scanner.re"
	{ RET(TK_Volatile); }
#line 2152 "src/sc_man_scanner.h"
yy328:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy329;
	if(yych != 't') goto yy174;
yy329:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy330;
	if(yych != 'u') goto yy174;
yy330:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy331;
	if(yych != 'a') goto yy174;
yy331:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy332;
	if(yych != 'l') goto yy174;
yy332:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy333;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy333;
			if(yych <= 'z') goto yy173;
		}
	}
yy333:
#line 134 "src/sc_man_scanner.re"
	{ RET(TK_Virtual); }
#line 2186 "src/sc_man_scanner.h"
yy334:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy351;
	if(yych == 'n') goto yy351;
	goto yy174;
yy335:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy347;
	if(yych == 'o') goto yy347;
	goto yy174;
yy336:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy343;
	if(yych == 't') goto yy343;
	goto yy174;
yy337:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy338;
	if(yych != 'h') goto yy174;
yy338:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy339;
	if(yych != 'o') goto yy174;
yy339:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy340;
	if(yych != 'r') goto yy174;
yy340:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy341;
	if(yych != 't') goto yy174;
yy341:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy342;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy342;
			if(yych <= 'z') goto yy173;
		}
	}
yy342:
#line 84 "src/sc_man_scanner.re"
	{ RET(TK_UShort); }
#line 2235 "src/sc_man_scanner.h"
yy343:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy344;
	if(yych != 'i') goto yy174;
yy344:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy345;
	if(yych != 'l') goto yy174;
yy345:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy346;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy346;
			if(yych <= 'z') goto yy173;
		}
	}
yy346:
#line 72 "src/sc_man_scanner.re"
	{ RET(TK_Until); }
#line 2261 "src/sc_man_scanner.h"
yy347:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy348;
	if(yych != 'n') goto yy174;
yy348:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy349;
	if(yych != 'g') goto yy174;
yy349:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy350;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy350;
			if(yych <= 'z') goto yy173;
		}
	}
yy350:
#line 88 "src/sc_man_scanner.re"
	{ RET(TK_ULong); }
#line 2287 "src/sc_man_scanner.h"
yy351:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy352;
	if(yych != 't') goto yy174;
yy352:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy353;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy353;
			if(yych <= 'z') goto yy173;
		}
	}
yy353:
#line 86 "src/sc_man_scanner.re"
	{ RET(TK_UInt); }
#line 2309 "src/sc_man_scanner.h"
yy354:
	yych = *++YYCURSOR;
	if(yych == 'Y') goto yy408;
	if(yych == 'y') goto yy408;
	goto yy174;
yy355:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy405;
	if(yych == 'l') goto yy405;
	goto yy174;
yy356:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy401;
	if(yych == 'o') goto yy401;
	goto yy174;
yy357:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy394;
	if(yych == 'n') goto yy394;
	goto yy174;
yy358:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy390;
	if(yych == 'u') goto yy390;
	goto yy174;
yy359:
	yych = *++YYCURSOR;
	if(yych <= 'R') {
		if(yych <= 'N') {
			if(yych == 'A') goto yy372;
			goto yy174;
		} else {
			if(yych <= 'O') goto yy373;
			if(yych <= 'Q') goto yy174;
			goto yy371;
		}
	} else {
		if(yych <= 'n') {
			if(yych == 'a') goto yy372;
			goto yy174;
		} else {
			if(yych <= 'o') goto yy373;
			if(yych == 'r') goto yy371;
			goto yy174;
		}
	}
yy360:
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy367;
	if(yych == 'p') goto yy367;
	goto yy174;
yy361:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy362;
	if(yych != 'i') goto yy174;
yy362:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy363;
	if(yych != 't') goto yy174;
yy363:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy364;
	if(yych != 'c') goto yy174;
yy364:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy365;
	if(yych != 'h') goto yy174;
yy365:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy366;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy366;
			if(yych <= 'z') goto yy173;
		}
	}
yy366:
#line 71 "src/sc_man_scanner.re"
	{ RET(TK_Switch); }
#line 2394 "src/sc_man_scanner.h"
yy367:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy368;
	if(yych != 'e') goto yy174;
yy368:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy369;
	if(yych != 'r') goto yy174;
yy369:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy370;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy370;
			if(yych <= 'z') goto yy173;
		}
	}
yy370:
#line 135 "src/sc_man_scanner.re"
	{ RET(TK_Super); }
#line 2420 "src/sc_man_scanner.h"
yy371:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych == 'I') goto yy382;
		if(yych <= 'T') goto yy174;
		goto yy383;
	} else {
		if(yych <= 'i') {
			if(yych <= 'h') goto yy174;
			goto yy382;
		} else {
			if(yych == 'u') goto yy383;
			goto yy174;
		}
	}
yy372:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy376;
	if(yych == 't') goto yy376;
	goto yy174;
yy373:
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy374;
	if(yych != 'p') goto yy174;
yy374:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy375;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy375;
			if(yych <= 'z') goto yy173;
		}
	}
yy375:
#line 138 "src/sc_man_scanner.re"
	{ RET(TK_Stop); }
#line 2462 "src/sc_man_scanner.h"
yy376:
	yych = *++YYCURSOR;
	if(yych <= 'I') {
		if(yych == 'E') goto yy377;
		if(yych <= 'H') goto yy174;
		goto yy379;
	} else {
		if(yych <= 'e') {
			if(yych <= 'd') goto yy174;
		} else {
			if(yych == 'i') goto yy379;
			goto yy174;
		}
	}
yy377:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy378;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy378;
			if(yych <= 'z') goto yy173;
		}
	}
yy378:
#line 97 "src/sc_man_scanner.re"
	{ RET(TK_State); }
#line 2494 "src/sc_man_scanner.h"
yy379:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy380;
	if(yych != 'c') goto yy174;
yy380:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy381;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy381;
			if(yych <= 'z') goto yy173;
		}
	}
yy381:
#line 115 "src/sc_man_scanner.re"
	{ RET(TK_Static); }
#line 2516 "src/sc_man_scanner.h"
yy382:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy387;
	if(yych == 'n') goto yy387;
	goto yy174;
yy383:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy384;
	if(yych != 'c') goto yy174;
yy384:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy385;
	if(yych != 't') goto yy174;
yy385:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy386;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy386;
			if(yych <= 'z') goto yy173;
		}
	}
yy386:
#line 90 "src/sc_man_scanner.re"
	{ RET(TK_Struct); }
#line 2547 "src/sc_man_scanner.h"
yy387:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy388;
	if(yych != 'g') goto yy174;
yy388:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy389;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy389;
			if(yych <= 'z') goto yy173;
		}
	}
yy389:
#line 95 "src/sc_man_scanner.re"
	{ RET(TK_String); }
#line 2569 "src/sc_man_scanner.h"
yy390:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy391;
	if(yych != 'n') goto yy174;
yy391:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy392;
	if(yych != 'd') goto yy174;
yy392:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy393;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy393;
			if(yych <= 'z') goto yy173;
		}
	}
yy393:
#line 96 "src/sc_man_scanner.re"
	{ RET(TK_Sound); }
#line 2595 "src/sc_man_scanner.h"
yy394:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy395;
	if(yych != 'g') goto yy174;
yy395:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy396;
	if(yych != 'u') goto yy174;
yy396:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy397;
	if(yych != 'l') goto yy174;
yy397:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy398;
	if(yych != 'a') goto yy174;
yy398:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy399;
	if(yych != 'r') goto yy174;
yy399:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy400;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy400;
			if(yych <= 'z') goto yy173;
		}
	}
yy400:
#line 128 "src/sc_man_scanner.re"
	{ RET(TK_Singular); }
#line 2633 "src/sc_man_scanner.h"
yy401:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy402;
	if(yych != 'r') goto yy174;
yy402:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy403;
	if(yych != 't') goto yy174;
yy403:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy404;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy404;
			if(yych <= 'z') goto yy173;
		}
	}
yy404:
#line 83 "src/sc_man_scanner.re"
	{ RET(TK_Short); }
#line 2659 "src/sc_man_scanner.h"
yy405:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy406;
	if(yych != 'f') goto yy174;
yy406:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy407;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy407;
			if(yych <= 'z') goto yy173;
		}
	}
yy407:
#line 137 "src/sc_man_scanner.re"
	{ RET(TK_Self); }
#line 2681 "src/sc_man_scanner.h"
yy408:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy409;
	if(yych != 't') goto yy174;
yy409:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy410;
	if(yych != 'e') goto yy174;
yy410:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy411;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy411;
			if(yych <= 'z') goto yy173;
		}
	}
yy411:
#line 82 "src/sc_man_scanner.re"
	{ RET(TK_SByte); }
#line 2707 "src/sc_man_scanner.h"
yy412:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy421;
	if(yych == 'n') goto yy421;
	goto yy174;
yy413:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych == 'F') goto yy415;
		if(yych <= 'S') goto yy174;
	} else {
		if(yych <= 'f') {
			if(yych <= 'e') goto yy174;
			goto yy415;
		} else {
			if(yych != 't') goto yy174;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy417;
	if(yych == 'u') goto yy417;
	goto yy174;
yy415:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy416;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy416;
			if(yych <= 'z') goto yy173;
		}
	}
yy416:
#line 113 "src/sc_man_scanner.re"
	{ RET(TK_Ref); }
#line 2747 "src/sc_man_scanner.h"
yy417:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy418;
	if(yych != 'r') goto yy174;
yy418:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy419;
	if(yych != 'n') goto yy174;
yy419:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy420;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy420;
			if(yych <= 'z') goto yy173;
		}
	}
yy420:
#line 70 "src/sc_man_scanner.re"
	{ RET(TK_Return); }
#line 2773 "src/sc_man_scanner.h"
yy421:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy422;
	if(yych != 'd') goto yy174;
yy422:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy423;
	if(yych != 'o') goto yy174;
yy423:
	yych = *++YYCURSOR;
	if(yych == 'M') goto yy424;
	if(yych != 'm') goto yy174;
yy424:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '@') {
		if(yych <= '1') {
			if(yych >= '0') goto yy173;
		} else {
			if(yych <= '2') goto yy426;
			if(yych <= '9') goto yy173;
		}
	} else {
		if(yych <= '_') {
			if(yych <= 'Z') goto yy173;
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy425;
			if(yych <= 'z') goto yy173;
		}
	}
yy425:
#line 151 "src/sc_man_scanner.re"
	{ RET(TK_Random); }
#line 2807 "src/sc_man_scanner.h"
yy426:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy427;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy427;
			if(yych <= 'z') goto yy173;
		}
	}
yy427:
#line 152 "src/sc_man_scanner.re"
	{ RET(TK_Random2); }
#line 2825 "src/sc_man_scanner.h"
yy428:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy429;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy429;
			if(yych <= 'z') goto yy173;
		}
	}
yy429:
#line 69 "src/sc_man_scanner.re"
	{ RET(TK_If); }
#line 2843 "src/sc_man_scanner.h"
yy430:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy451;
	if(yych == 'n') goto yy451;
	goto yy174;
yy431:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych <= 'R') goto yy174;
		if(yych <= 'S') goto yy442;
		goto yy440;
	} else {
		if(yych <= 'r') goto yy174;
		if(yych <= 's') goto yy442;
		if(yych <= 't') goto yy440;
		goto yy174;
	}
yy432:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy433;
	if(yych != 'e') goto yy174;
yy433:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy434;
	if(yych != 'r') goto yy174;
yy434:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy435;
	if(yych != 'a') goto yy174;
yy435:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy436;
	if(yych != 't') goto yy174;
yy436:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy437;
	if(yych != 'o') goto yy174;
yy437:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy438;
	if(yych != 'r') goto yy174;
yy438:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy439;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy439;
			if(yych <= 'z') goto yy173;
		}
	}
yy439:
#line 131 "src/sc_man_scanner.re"
	{ RET(TK_Iterator); }
#line 2902 "src/sc_man_scanner.h"
yy440:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy441;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy441;
			if(yych <= 'z') goto yy173;
		}
	}
yy441:
#line 85 "src/sc_man_scanner.re"
	{ RET(TK_Int); }
#line 2920 "src/sc_man_scanner.h"
yy442:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy443;
	if(yych != 't') goto yy174;
yy443:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy444;
	if(yych != 'a') goto yy174;
yy444:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy445;
	if(yych != 'n') goto yy174;
yy445:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy446;
	if(yych != 'c') goto yy174;
yy446:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy447;
	if(yych != 'e') goto yy174;
yy447:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy448;
	if(yych != 'o') goto yy174;
yy448:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy449;
	if(yych != 'f') goto yy174;
yy449:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy450;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy450;
			if(yych <= 'z') goto yy173;
		}
	}
yy450:
#line 107 "src/sc_man_scanner.re"
	{ RET(TK_InstanceOf); }
#line 2966 "src/sc_man_scanner.h"
yy451:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy452;
	if(yych != 'o') goto yy174;
yy452:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy453;
	if(yych != 'r') goto yy174;
yy453:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy454;
	if(yych != 'e') goto yy174;
yy454:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy455;
	if(yych != 's') goto yy174;
yy455:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy456;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy456;
			if(yych <= 'z') goto yy173;
		}
	}
yy456:
#line 125 "src/sc_man_scanner.re"
	{ RET(TK_Ignores); }
#line 3000 "src/sc_man_scanner.h"
yy457:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy462;
	if(yych == 'o') goto yy462;
	goto yy174;
yy458:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy459;
	if(yych != 't') goto yy174;
yy459:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy460;
	if(yych != 'o') goto yy174;
yy460:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy461;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy461;
			if(yych <= 'z') goto yy173;
		}
	}
yy461:
#line 68 "src/sc_man_scanner.re"
	{ RET(TK_Goto); }
#line 3031 "src/sc_man_scanner.h"
yy462:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy463;
	if(yych != 'b') goto yy174;
yy463:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy464;
	if(yych != 'a') goto yy174;
yy464:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy465;
	if(yych != 'l') goto yy174;
yy465:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy466;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy466;
			if(yych <= 'z') goto yy173;
		}
	}
yy466:
#line 136 "src/sc_man_scanner.re"
	{ RET(TK_Global); }
#line 3061 "src/sc_man_scanner.h"
yy467:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy492;
	if(yych == 'l') goto yy492;
	goto yy174;
yy468:
	yych = *++YYCURSOR;
	if(yych <= 'X') {
		if(yych == 'N') goto yy482;
		if(yych <= 'W') goto yy174;
		goto yy483;
	} else {
		if(yych <= 'n') {
			if(yych <= 'm') goto yy174;
			goto yy482;
		} else {
			if(yych == 'x') goto yy483;
			goto yy174;
		}
	}
yy469:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy478;
	if(yych == 'o') goto yy478;
	goto yy174;
yy470:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy471;
	if(yych != 'r') goto yy174;
yy471:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '@') {
			if(yych <= '/') goto yy472;
			if(yych <= '9') goto yy173;
		} else {
			if(yych == 'E') goto yy473;
			goto yy173;
		}
	} else {
		if(yych <= '`') {
			if(yych == '_') goto yy173;
		} else {
			if(yych == 'e') goto yy473;
			if(yych <= 'z') goto yy173;
		}
	}
yy472:
#line 67 "src/sc_man_scanner.re"
	{ RET(TK_For); }
#line 3112 "src/sc_man_scanner.h"
yy473:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy474;
	if(yych != 'a') goto yy174;
yy474:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy475;
	if(yych != 'c') goto yy174;
yy475:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy476;
	if(yych != 'h') goto yy174;
yy476:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy477;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy477;
			if(yych <= 'z') goto yy173;
		}
	}
yy477:
#line 102 "src/sc_man_scanner.re"
	{ RET(TK_ForEach); }
#line 3142 "src/sc_man_scanner.h"
yy478:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy479;
	if(yych != 'a') goto yy174;
yy479:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy480;
	if(yych != 't') goto yy174;
yy480:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy481;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy481;
			if(yych <= 'z') goto yy173;
		}
	}
yy481:
#line 78 "src/sc_man_scanner.re"
	{ RET(TK_Float); }
#line 3168 "src/sc_man_scanner.h"
yy482:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy489;
	if(yych == 'a') goto yy489;
	goto yy174;
yy483:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy484;
	if(yych != 'e') goto yy174;
yy484:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy485;
	if(yych != 'd') goto yy174;
yy485:
	yych = *++YYCURSOR;
	if(yych != '_') goto yy174;
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy487;
	if(yych != 't') goto yy174;
yy487:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy488;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy488;
			if(yych <= 'z') goto yy173;
		}
	}
yy488:
#line 148 "src/sc_man_scanner.re"
	{ RET(TK_Fixed_t); }
#line 3205 "src/sc_man_scanner.h"
yy489:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy490;
	if(yych != 'l') goto yy174;
yy490:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy491;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy491;
			if(yych <= 'z') goto yy173;
		}
	}
yy491:
#line 117 "src/sc_man_scanner.re"
	{ RET(TK_Final); }
#line 3227 "src/sc_man_scanner.h"
yy492:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy493;
	if(yych != 's') goto yy174;
yy493:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy494;
	if(yych != 'e') goto yy174;
yy494:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy495;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy495;
			if(yych <= 'z') goto yy173;
		}
	}
yy495:
#line 104 "src/sc_man_scanner.re"
	{ RET(TK_False); }
#line 3253 "src/sc_man_scanner.h"
yy496:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy521;
	if(yych == 's') goto yy521;
	goto yy174;
yy497:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy518;
	if(yych == 'u') goto yy518;
	goto yy174;
yy498:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy514;
	if(yych == 'e') goto yy514;
	goto yy174;
yy499:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych <= 'O') {
			if(yych != 'E') goto yy174;
		} else {
			if(yych <= 'P') goto yy502;
			if(yych <= 'S') goto yy174;
			goto yy501;
		}
	} else {
		if(yych <= 'o') {
			if(yych != 'e') goto yy174;
		} else {
			if(yych <= 'p') goto yy502;
			if(yych == 't') goto yy501;
			goto yy174;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy512;
	if(yych == 'c') goto yy512;
	goto yy174;
yy501:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy507;
	if(yych == 'e') goto yy507;
	goto yy174;
yy502:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy503;
	if(yych != 'o') goto yy174;
yy503:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy504;
	if(yych != 'r') goto yy174;
yy504:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy505;
	if(yych != 't') goto yy174;
yy505:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy506;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy506;
			if(yych <= 'z') goto yy173;
		}
	}
yy506:
#line 133 "src/sc_man_scanner.re"
	{ RET(TK_Export); }
#line 3326 "src/sc_man_scanner.h"
yy507:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy508;
	if(yych != 'n') goto yy174;
yy508:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy509;
	if(yych != 'd') goto yy174;
yy509:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy510;
	if(yych != 's') goto yy174;
yy510:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy511;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy511;
			if(yych <= 'z') goto yy173;
		}
	}
yy511:
#line 119 "src/sc_man_scanner.re"
	{ RET(TK_Extends); }
#line 3356 "src/sc_man_scanner.h"
yy512:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy513;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy513;
			if(yych <= 'z') goto yy173;
		}
	}
yy513:
#line 109 "src/sc_man_scanner.re"
	{ RET(TK_Exec); }
#line 3374 "src/sc_man_scanner.h"
yy514:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy515;
	if(yych != 'n') goto yy174;
yy515:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy516;
	if(yych != 't') goto yy174;
yy516:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy517;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy517;
			if(yych <= 'z') goto yy173;
		}
	}
yy517:
#line 114 "src/sc_man_scanner.re"
	{ RET(TK_Event); }
#line 3400 "src/sc_man_scanner.h"
yy518:
	yych = *++YYCURSOR;
	if(yych == 'M') goto yy519;
	if(yych != 'm') goto yy174;
yy519:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy520;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy520;
			if(yych <= 'z') goto yy173;
		}
	}
yy520:
#line 93 "src/sc_man_scanner.re"
	{ RET(TK_Enum); }
#line 3422 "src/sc_man_scanner.h"
yy521:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy522;
	if(yych != 'e') goto yy174;
yy522:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy523;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy523;
			if(yych <= 'z') goto yy173;
		}
	}
yy523:
#line 66 "src/sc_man_scanner.re"
	{ RET(TK_Else); }
#line 3444 "src/sc_man_scanner.h"
yy524:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy534;
	if(yych == 'f') goto yy534;
	goto yy174;
yy525:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '@') {
			if(yych <= '/') goto yy526;
			if(yych <= '9') goto yy173;
		} else {
			if(yych <= 'S') goto yy173;
			if(yych <= 'T') goto yy528;
			if(yych <= 'U') goto yy527;
			goto yy173;
		}
	} else {
		if(yych <= 's') {
			if(yych == '_') goto yy173;
			if(yych >= 'a') goto yy173;
		} else {
			if(yych <= 't') goto yy528;
			if(yych <= 'u') goto yy527;
			if(yych <= 'z') goto yy173;
		}
	}
yy526:
#line 65 "src/sc_man_scanner.re"
	{ RET(TK_Do); }
#line 3475 "src/sc_man_scanner.h"
yy527:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy530;
	if(yych == 'b') goto yy530;
	goto yy174;
yy528:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy529;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy529;
			if(yych <= 'z') goto yy173;
		}
	}
yy529:
#line 123 "src/sc_man_scanner.re"
	{ RET(TK_Dot); }
#line 3498 "src/sc_man_scanner.h"
yy530:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy531;
	if(yych != 'l') goto yy174;
yy531:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy532;
	if(yych != 'e') goto yy174;
yy532:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy533;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy533;
			if(yych <= 'z') goto yy173;
		}
	}
yy533:
#line 79 "src/sc_man_scanner.re"
	{ RET(TK_Double); }
#line 3524 "src/sc_man_scanner.h"
yy534:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy535;
	if(yych != 'a') goto yy174;
yy535:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy536;
	if(yych != 'u') goto yy174;
yy536:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy537;
	if(yych != 'l') goto yy174;
yy537:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy538;
	if(yych != 't') goto yy174;
yy538:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '@') {
			if(yych <= '/') goto yy539;
			if(yych <= '9') goto yy173;
		} else {
			if(yych == 'P') goto yy540;
			goto yy173;
		}
	} else {
		if(yych <= '`') {
			if(yych == '_') goto yy173;
		} else {
			if(yych == 'p') goto yy540;
			if(yych <= 'z') goto yy173;
		}
	}
yy539:
#line 64 "src/sc_man_scanner.re"
	{ RET(TK_Default); }
#line 3562 "src/sc_man_scanner.h"
yy540:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy541;
	if(yych != 'r') goto yy174;
yy541:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy542;
	if(yych != 'o') goto yy174;
yy542:
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy543;
	if(yych != 'p') goto yy174;
yy543:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy544;
	if(yych != 'e') goto yy174;
yy544:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy545;
	if(yych != 'r') goto yy174;
yy545:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy546;
	if(yych != 't') goto yy174;
yy546:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy547;
	if(yych != 'i') goto yy174;
yy547:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy548;
	if(yych != 'e') goto yy174;
yy548:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy549;
	if(yych != 's') goto yy174;
yy549:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy550;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy550;
			if(yych <= 'z') goto yy173;
		}
	}
yy550:
#line 110 "src/sc_man_scanner.re"
	{ RET(TK_DefaultProperties); }
#line 3616 "src/sc_man_scanner.h"
yy551:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy590;
	if(yych == 's') goto yy590;
	goto yy174;
yy552:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy587;
	if(yych == 'a') goto yy587;
	goto yy174;
yy553:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy583;
	if(yych == 'a') goto yy583;
	goto yy174;
yy554:
	yych = *++YYCURSOR;
	if(yych <= 'N') {
		if(yych <= 'K') {
			if(yych == 'E') goto yy562;
			goto yy174;
		} else {
			if(yych <= 'L') goto yy561;
			if(yych <= 'M') goto yy174;
			goto yy560;
		}
	} else {
		if(yych <= 'k') {
			if(yych == 'e') goto yy562;
			goto yy174;
		} else {
			if(yych <= 'l') goto yy561;
			if(yych == 'n') goto yy560;
			goto yy174;
		}
	}
yy555:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy556;
	if(yych != 'o') goto yy174;
yy556:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy557;
	if(yych != 's') goto yy174;
yy557:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy558;
	if(yych != 's') goto yy174;
yy558:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy559;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy559;
			if(yych <= 'z') goto yy173;
		}
	}
yy559:
#line 124 "src/sc_man_scanner.re"
	{ RET(TK_Cross); }
#line 3682 "src/sc_man_scanner.h"
yy560:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych <= 'F') {
			if(yych <= 'E') goto yy174;
			goto yy570;
		} else {
			if(yych <= 'R') goto yy174;
			if(yych <= 'S') goto yy571;
			goto yy572;
		}
	} else {
		if(yych <= 'r') {
			if(yych == 'f') goto yy570;
			goto yy174;
		} else {
			if(yych <= 's') goto yy571;
			if(yych <= 't') goto yy572;
			goto yy174;
		}
	}
yy561:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy567;
	if(yych == 'o') goto yy567;
	goto yy174;
yy562:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy563;
	if(yych != 'r') goto yy174;
yy563:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy564;
	if(yych != 'c') goto yy174;
yy564:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy565;
	if(yych != 'e') goto yy174;
yy565:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy566;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy566;
			if(yych <= 'z') goto yy173;
		}
	}
yy566:
#line 130 "src/sc_man_scanner.re"
	{ RET(TK_Coerce); }
#line 3738 "src/sc_man_scanner.h"
yy567:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy568;
	if(yych != 'r') goto yy174;
yy568:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy569;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy569;
			if(yych <= 'z') goto yy173;
		}
	}
yy569:
#line 98 "src/sc_man_scanner.re"
	{ RET(TK_Color); }
#line 3760 "src/sc_man_scanner.h"
yy570:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy580;
	if(yych == 'i') goto yy580;
	goto yy174;
yy571:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy578;
	if(yych == 't') goto yy578;
	goto yy174;
yy572:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy573;
	if(yych != 'i') goto yy174;
yy573:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy574;
	if(yych != 'n') goto yy174;
yy574:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy575;
	if(yych != 'u') goto yy174;
yy575:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy576;
	if(yych != 'e') goto yy174;
yy576:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy577;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy577;
			if(yych <= 'z') goto yy173;
		}
	}
yy577:
#line 63 "src/sc_man_scanner.re"
	{ RET(TK_Continue); }
#line 3804 "src/sc_man_scanner.h"
yy578:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy579;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy579;
			if(yych <= 'z') goto yy173;
		}
	}
yy579:
#line 62 "src/sc_man_scanner.re"
	{ RET(TK_Const); }
#line 3822 "src/sc_man_scanner.h"
yy580:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy581;
	if(yych != 'g') goto yy174;
yy581:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy582;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy582;
			if(yych <= 'z') goto yy173;
		}
	}
yy582:
#line 129 "src/sc_man_scanner.re"
	{ RET(TK_Config); }
#line 3844 "src/sc_man_scanner.h"
yy583:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy584;
	if(yych != 's') goto yy174;
yy584:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy585;
	if(yych != 's') goto yy174;
yy585:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy586;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy586;
			if(yych <= 'z') goto yy173;
		}
	}
yy586:
#line 91 "src/sc_man_scanner.re"
	{ RET(TK_Class); }
#line 3870 "src/sc_man_scanner.h"
yy587:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy588;
	if(yych != 'r') goto yy174;
yy588:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy589;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy589;
			if(yych <= 'z') goto yy173;
		}
	}
yy589:
#line 80 "src/sc_man_scanner.re"
	{ RET(TK_Char); }
#line 3892 "src/sc_man_scanner.h"
yy590:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy591;
	if(yych != 'e') goto yy174;
yy591:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy592;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy592;
			if(yych <= 'z') goto yy173;
		}
	}
yy592:
#line 61 "src/sc_man_scanner.re"
	{ RET(TK_Case); }
#line 3914 "src/sc_man_scanner.h"
yy593:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy608;
	if(yych == 'o') goto yy608;
	goto yy174;
yy594:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy599;
	if(yych == 'e') goto yy599;
	goto yy174;
yy595:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy596;
	if(yych != 't') goto yy174;
yy596:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy597;
	if(yych != 'e') goto yy174;
yy597:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy598;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy598;
			if(yych <= 'z') goto yy173;
		}
	}
yy598:
#line 81 "src/sc_man_scanner.re"
	{ RET(TK_Byte); }
#line 3950 "src/sc_man_scanner.h"
yy599:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy600;
	if(yych != 'a') goto yy174;
yy600:
	yych = *++YYCURSOR;
	if(yych == 'K') goto yy601;
	if(yych != 'k') goto yy174;
yy601:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '9') {
			if(yych >= '0') goto yy173;
		} else {
			if(yych <= '@') goto yy602;
			if(yych <= 'A') goto yy603;
			goto yy173;
		}
	} else {
		if(yych <= '`') {
			if(yych == '_') goto yy173;
		} else {
			if(yych <= 'a') goto yy603;
			if(yych <= 'z') goto yy173;
		}
	}
yy602:
#line 60 "src/sc_man_scanner.re"
	{ RET(TK_Break); }
#line 3980 "src/sc_man_scanner.h"
yy603:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy604;
	if(yych != 'b') goto yy174;
yy604:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy605;
	if(yych != 'l') goto yy174;
yy605:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy606;
	if(yych != 'e') goto yy174;
yy606:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy607;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy607;
			if(yych <= 'z') goto yy173;
		}
	}
yy607:
#line 146 "src/sc_man_scanner.re"
	{ RET(TK_Breakable); }
#line 4010 "src/sc_man_scanner.h"
yy608:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy609;
	if(yych != 'l') goto yy174;
yy609:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy610;
		if(yych <= '9') goto yy173;
		if(yych >= 'A') goto yy173;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy173;
		} else {
			if(yych <= '`') goto yy610;
			if(yych <= 'z') goto yy173;
		}
	}
yy610:
#line 77 "src/sc_man_scanner.re"
	{ RET(TK_Bool); }
#line 4032 "src/sc_man_scanner.h"
yy611:
	++YYCURSOR;
#line 175 "src/sc_man_scanner.re"
	{ RET(TK_DivEq); }
#line 4037 "src/sc_man_scanner.h"
yy613:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x0A) goto yy617;
	goto yy613;
yy615:
	++YYCURSOR;
#line 56 "src/sc_man_scanner.re"
	{ goto comment; }
#line 4048 "src/sc_man_scanner.h"
yy617:
	++YYCURSOR;
#line 57 "src/sc_man_scanner.re"
	{ goto newline; }
#line 4053 "src/sc_man_scanner.h"
}
#line 223 "src/sc_man_scanner.re"

	}
	if (!CMode)	// The classic Hexen scanner.
	{
	
#line 4061 "src/sc_man_scanner.h"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '/') {
		if(yych <= ' ') {
			if(yych == 0x0A) goto yy627;
			goto yy625;
		} else {
			if(yych == '"') goto yy629;
			if(yych <= '.') goto yy633;
			goto yy622;
		}
	} else {
		if(yych <= '<') {
			if(yych == ';') goto yy624;
			goto yy633;
		} else {
			if(yych <= '=') goto yy631;
			if(yych <= 'z') goto yy633;
			if(yych <= '}') goto yy631;
			goto yy633;
		}
	}
yy621:
#line 238 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4090 "src/sc_man_scanner.h"
yy622:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '/') {
		if(yych <= '"') {
			if(yych == '!') goto yy638;
		} else {
			if(yych == '*') goto yy646;
			if(yych <= '.') goto yy638;
			goto yy642;
		}
	} else {
		if(yych <= '<') {
			if(yych != ';') goto yy638;
		} else {
			if(yych <= '=') goto yy623;
			if(yych <= 'z') goto yy638;
			if(yych >= '~') goto yy638;
		}
	}
yy623:
#line 240 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4114 "src/sc_man_scanner.h"
yy624:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy643;
yy625:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy641;
yy626:
#line 231 "src/sc_man_scanner.re"
	{ goto std1; }
#line 4126 "src/sc_man_scanner.h"
yy627:
	++YYCURSOR;
#line 232 "src/sc_man_scanner.re"
	{ goto newline; }
#line 4131 "src/sc_man_scanner.h"
yy629:
	++YYCURSOR;
#line 233 "src/sc_man_scanner.re"
	{ goto string; }
#line 4136 "src/sc_man_scanner.h"
yy631:
	++YYCURSOR;
#line 235 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4141 "src/sc_man_scanner.h"
yy633:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy637;
yy634:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '/') {
		if(yych <= '"') {
			if(yych == '!') goto yy638;
		} else {
			if(yych == '*') goto yy635;
			if(yych <= '.') goto yy638;
		}
	} else {
		if(yych <= '<') {
			if(yych != ';') goto yy638;
		} else {
			if(yych <= '=') goto yy635;
			if(yych <= 'z') goto yy638;
			if(yych >= '~') goto yy638;
		}
	}
yy635:
	YYCURSOR = YYMARKER;
	if(yyaccept <= 0) {
		goto yy623;
	} else {
		goto yy621;
	}
yy636:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy637:
	if(yych <= ':') {
		if(yych <= '"') {
			if(yych == '!') goto yy636;
			goto yy621;
		} else {
			if(yych == '/') goto yy634;
			goto yy636;
		}
	} else {
		if(yych <= '=') {
			if(yych == '<') goto yy636;
			goto yy621;
		} else {
			if(yych <= 'z') goto yy636;
			if(yych <= '}') goto yy621;
			goto yy636;
		}
	}
yy638:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= ':') {
		if(yych <= '"') {
			if(yych == '!') goto yy638;
			goto yy621;
		} else {
			if(yych == '/') goto yy634;
			goto yy638;
		}
	} else {
		if(yych <= '=') {
			if(yych == '<') goto yy638;
			goto yy621;
		} else {
			if(yych <= 'z') goto yy638;
			if(yych <= '}') goto yy621;
			goto yy638;
		}
	}
yy640:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy641:
	if(yych == 0x0A) goto yy626;
	if(yych <= ' ') goto yy640;
	goto yy626;
yy642:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy643:
	if(yych != 0x0A) goto yy642;
	++YYCURSOR;
#line 229 "src/sc_man_scanner.re"
	{ goto newline; }
#line 4237 "src/sc_man_scanner.h"
yy646:
	++YYCURSOR;
#line 228 "src/sc_man_scanner.re"
	{ goto comment; }
#line 4242 "src/sc_man_scanner.h"
}
#line 241 "src/sc_man_scanner.re"

	}
	else		// A modified Hexen scanner for DECORATE.
	{
	
#line 4250 "src/sc_man_scanner.h"
{
	YYCTYPE yych;
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= ':') {
		if(yych <= '&') {
			if(yych <= ' ') {
				if(yych == 0x0A) goto yy654;
				goto yy652;
			} else {
				if(yych == '"') goto yy656;
				if(yych <= '%') goto yy669;
				goto yy664;
			}
		} else {
			if(yych <= '-') {
				if(yych <= '\'') goto yy670;
				if(yych <= ',') goto yy669;
				goto yy658;
			} else {
				if(yych <= '.') goto yy662;
				if(yych <= '/') goto yy650;
				if(yych <= '9') goto yy660;
				goto yy663;
			}
		}
	} else {
		if(yych <= '^') {
			if(yych <= '=') {
				if(yych <= ';') goto yy669;
				if(yych <= '<') goto yy667;
				goto yy665;
			} else {
				if(yych <= '>') goto yy668;
				if(yych <= '@') goto yy669;
				if(yych <= 'Z') goto yy670;
				goto yy669;
			}
		} else {
			if(yych <= 'z') {
				if(yych == '`') goto yy669;
				goto yy670;
			} else {
				if(yych == '|') goto yy666;
				if(yych <= '~') goto yy669;
				goto yy670;
			}
		}
	}
yy650:
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '*') goto yy696;
	if(yych == '/') goto yy694;
yy651:
#line 261 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4307 "src/sc_man_scanner.h"
yy652:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy693;
yy653:
#line 249 "src/sc_man_scanner.re"
	{ goto std1; }
#line 4315 "src/sc_man_scanner.h"
yy654:
	++YYCURSOR;
#line 250 "src/sc_man_scanner.re"
	{ goto newline; }
#line 4320 "src/sc_man_scanner.h"
yy656:
	++YYCURSOR;
#line 251 "src/sc_man_scanner.re"
	{ goto string; }
#line 4325 "src/sc_man_scanner.h"
yy658:
	++YYCURSOR;
#line 253 "src/sc_man_scanner.re"
	{ goto negative_check; }
#line 4330 "src/sc_man_scanner.h"
yy660:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '.') goto yy690;
	if(yych <= '/') goto yy672;
	if(yych <= '9') goto yy688;
	goto yy672;
yy661:
#line 262 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4340 "src/sc_man_scanner.h"
yy662:
	yych = *++YYCURSOR;
	if(yych <= '/') goto yy651;
	if(yych <= '9') goto yy685;
	goto yy651;
yy663:
	yych = *++YYCURSOR;
	if(yych == ':') goto yy683;
	goto yy651;
yy664:
	yych = *++YYCURSOR;
	if(yych == '&') goto yy681;
	goto yy651;
yy665:
	yych = *++YYCURSOR;
	if(yych == '=') goto yy679;
	goto yy651;
yy666:
	yych = *++YYCURSOR;
	if(yych == '|') goto yy677;
	goto yy651;
yy667:
	yych = *++YYCURSOR;
	if(yych == '<') goto yy675;
	goto yy651;
yy668:
	yych = *++YYCURSOR;
	if(yych == '>') goto yy673;
	goto yy651;
yy669:
	yych = *++YYCURSOR;
	goto yy651;
yy670:
	yych = *++YYCURSOR;
	goto yy672;
yy671:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy672:
	if(yych <= 'Z') {
		if(yych <= '/') {
			if(yych == '\'') goto yy671;
			goto yy661;
		} else {
			if(yych <= '9') goto yy671;
			if(yych <= '@') goto yy661;
			goto yy671;
		}
	} else {
		if(yych <= '`') {
			if(yych == '_') goto yy671;
			goto yy661;
		} else {
			if(yych <= 'z') goto yy671;
			if(yych <= '~') goto yy661;
			goto yy671;
		}
	}
yy673:
	++YYCURSOR;
#line 260 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4404 "src/sc_man_scanner.h"
yy675:
	++YYCURSOR;
#line 259 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4409 "src/sc_man_scanner.h"
yy677:
	++YYCURSOR;
#line 258 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4414 "src/sc_man_scanner.h"
yy679:
	++YYCURSOR;
#line 257 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4419 "src/sc_man_scanner.h"
yy681:
	++YYCURSOR;
#line 256 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4424 "src/sc_man_scanner.h"
yy683:
	++YYCURSOR;
#line 255 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4429 "src/sc_man_scanner.h"
yy685:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '/') goto yy687;
	if(yych <= '9') goto yy685;
yy687:
#line 254 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4439 "src/sc_man_scanner.h"
yy688:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@') {
		if(yych <= '-') {
			if(yych == '\'') goto yy671;
			goto yy661;
		} else {
			if(yych <= '.') goto yy690;
			if(yych <= '/') goto yy661;
			if(yych <= '9') goto yy688;
			goto yy661;
		}
	} else {
		if(yych <= '_') {
			if(yych <= 'Z') goto yy671;
			if(yych <= '^') goto yy661;
			goto yy671;
		} else {
			if(yych <= '`') goto yy661;
			if(yych <= 'z') goto yy671;
			if(yych <= '~') goto yy661;
			goto yy671;
		}
	}
yy690:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '/') goto yy687;
	if(yych <= '9') goto yy690;
	goto yy687;
yy692:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy693:
	if(yych == 0x0A) goto yy653;
	if(yych <= ' ') goto yy692;
	goto yy653;
yy694:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x0A) goto yy698;
	goto yy694;
yy696:
	++YYCURSOR;
#line 246 "src/sc_man_scanner.re"
	{ goto comment; }
#line 4491 "src/sc_man_scanner.h"
yy698:
	++YYCURSOR;
#line 247 "src/sc_man_scanner.re"
	{ goto newline; }
#line 4496 "src/sc_man_scanner.h"
}
#line 265 "src/sc_man_scanner.re"

	}

negative_check:
	// re2c doesn't have enough state to handle '-' as the start of a negative number
	// and as its own token, so help it out a little.
	TokenType = '-';
	if (YYCURSOR >= YYLIMIT)
	{
		goto normal_token;
	}
	if (*YYCURSOR >= '0' && *YYCURSOR <= '9')
	{
		goto std2;
	}
	if (*YYCURSOR != '.' || YYCURSOR+1 >= YYLIMIT)
	{
		goto normal_token;
	}
	if (*(YYCURSOR+1) >= '0' && *YYCURSOR <= '9')
	{
		goto std2;
	}
	goto normal_token;

comment:

#line 4526 "src/sc_man_scanner.h"
{
	YYCTYPE yych;
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych == 0x0A) goto yy704;
	if(yych != '*') goto yy706;
	++YYCURSOR;
	if((yych = *YYCURSOR) == '/') goto yy707;
yy703:
#line 314 "src/sc_man_scanner.re"
	{ goto comment; }
#line 4538 "src/sc_man_scanner.h"
yy704:
	++YYCURSOR;
#line 303 "src/sc_man_scanner.re"
	{
			if (YYCURSOR >= YYLIMIT)
			{
				ScriptPtr = ScriptEndPtr;
				return_val = false;
				goto end;
			}
			Line++;
			Crossed = true;
			goto comment;
		}
#line 4553 "src/sc_man_scanner.h"
yy706:
	yych = *++YYCURSOR;
	goto yy703;
yy707:
	++YYCURSOR;
#line 293 "src/sc_man_scanner.re"
	{
			if (YYCURSOR >= YYLIMIT)
			{
				ScriptPtr = ScriptEndPtr;
				return_val = false;
				goto end;
			}
			goto std1;
		}
#line 4569 "src/sc_man_scanner.h"
}
#line 315 "src/sc_man_scanner.re"


newline:
	if (YYCURSOR >= YYLIMIT)
	{
		ScriptPtr = ScriptEndPtr;
		return_val = false;
		goto end;
	}
	Line++;
	Crossed = true;
	goto std1;

normal_token:
	ScriptPtr = (YYCURSOR >= YYLIMIT) ? ScriptEndPtr : cursor;
	StringLen = int(ScriptPtr - tok);
	if (tokens && (TokenType == TK_StringConst || TokenType == TK_NameConst))
	{
		StringLen -= 2;
		if (StringLen >= MAX_STRING_SIZE)
		{
			BigStringBuffer = FString(tok+1, StringLen);
		}
		else
		{
			memcpy (StringBuffer, tok+1, StringLen);
		}
	}
	else
	{
		if (StringLen >= MAX_STRING_SIZE)
		{
			BigStringBuffer = FString(tok, StringLen);
		}
		else
		{
			memcpy (StringBuffer, tok, StringLen);
		}
	}
	if (StringLen < MAX_STRING_SIZE)
	{
		String = StringBuffer;
		StringBuffer[StringLen] = '\0';
	}
	else
	{
		String = BigStringBuffer.LockBuffer();
	}
	return_val = true;
	goto end;

string:
	if (YYLIMIT != ScriptEndPtr)
	{
		ScriptPtr = ScriptEndPtr;
		return_val = false;
		goto end;
	}
	ScriptPtr = cursor;
	BigStringBuffer = "";
	for (StringLen = 0; cursor < YYLIMIT; ++cursor)
	{
		if (Escape && *cursor == '\\' && *(cursor + 1) == '"')
		{
			cursor++;
		}
		else if (*cursor == '\r' && *(cursor + 1) == '\n')
		{
			cursor++;	// convert CR-LF to simply LF
		}
		else if (*cursor == '"')
		{
			break;
		}
		if (*cursor == '\n')
		{
			if (CMode)
			{
				if (!Escape || StringLen == 0 || String[StringLen - 1] != '\\')
				{
					ScriptError ("Unterminated string constant");
				}
				else
				{
					StringLen--;		// overwrite the \ character with \n
				}
			}
			Line++;
			Crossed = true;
		}
		if (StringLen == MAX_STRING_SIZE)
		{
			BigStringBuffer.AppendCStrPart(StringBuffer, StringLen);
			StringLen = 0;
		}
		StringBuffer[StringLen++] = *cursor;
	}
	if (BigStringBuffer.IsNotEmpty() || StringLen == MAX_STRING_SIZE)
	{
		BigStringBuffer.AppendCStrPart(StringBuffer, StringLen);
		String = BigStringBuffer.LockBuffer();
		StringLen = int(BigStringBuffer.Len());
	}
	else
	{
		String = StringBuffer;
		StringBuffer[StringLen] = '\0';
	}
	ScriptPtr = cursor + 1;
	return_val = true;
end:
